# Site settings
title: 风吹云飘的技术博客
email: shen.yi20@zte.com.cn
description: > #风吹云飘的技术博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://liuyanwei.jumppo.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
#markdown: kramdown
permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: 风吹云飘
  email: shen.yi20@zte.com.cn  
  github: https://github.com/weliknYi
title: 风吹云飘的技术博客                             #自定义常量

# avatar头像及Favicon
avatar: 
#favicon: 

locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: redcarpet                         #markdown解释器

# google analytics 设置
#ga:
#  id:
#  url:
#

# disqus 设置
disqus:
  shortname: 